
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

inhibit_all_warnings!

target 'samples' do
  # ReactNative
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'MandMobileRN', :path => '../node_modules/mand-mobile-rn'#, :subspecs => ['Core', 'MDNumberKeyboard', 'MDRefreshControl', 'MDImagePicker']
end
